name: ci

on:
  pull_request:
  push:
    branches:
      - master
    tags-ignore:
      - v.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: niden/actions-memcached@v7
      - name: Restore Cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: 1.14.x
      - name: Run unit tests
        run: make test TEST_FLAGS="-race -tags integration -timeout 5m"
      - name: Check codegen
        run: make check-generated
      - name: Build containers
        run: make all
